// Generated by CoffeeScript 1.7.1

/*
window.onload = ->
	document.addEventListener('deviceready', on_devide_ready, no)

show_ad = (bshow) ->
	if window.plugins and window.plugins.AdMob
		am = window.plugins.AdMob
		am.showAd(bshow)
	else
		 *alert('AdMob plugin not available/ready.')

on_devide_ready = ->
	admob_ios_key     = '-'
	admob_android_key = 'ca-app-pub-8910256399447461/6325603433'

	ad_id = admob_android_key
	 *ad_id = if navigator.userAgent.indexOf('Android') >=0 then admob_android_key else admob_ios_key

	if window.plugins and window.plugins.AdMob
		am = window.plugins.AdMob

		am.createBannerView(
			publisherId: ad_id
			adSize:      am.AD_SIZE.BANNER
			bannerAtTop: no
		, ->
			am.requestAd(isTesting: yes, extras:
				color_bg:     'AAAAFF'
				color_bg_top: 'FFFFFF'
				color_border: 'FFFFFF'
				color_link:   '000080'
				color_text:   '808080'
				color_url:    '008000'
			, ->
				show_ad(yes)
			, ->
				 *alert('failed to request ad')
			)
		, ->
			 *alert('failed to create ad view')
		)
	else
		 *alert('AdMob plugin not available/ready.')
 */

/*
initAd = ->
	alert('4')
	if window.plugins and window.plugins.AdMob
		alert('5')
		ad_units =
			ios:
				banner:       'ca-app-pub-8910256399447461/6325603433'
				interstitial: 'ca-app-pub-8910256399447461/6325603433'

			android:
				banner:       'ca-app-pub-8910256399447461/6325603433'
				interstitial: 'ca-app-pub-8910256399447461/6325603433'

		admobid = if /(android)/i.test(navigator.userAgent) then ad_units.android else ad_units.ios

		window.plugins.AdMob.setOptions(
			publisherId:      admobid.banner
			interstitialAdId: admobid.interstitial
			bannerAtTop:      no
			overlap:          no
			offsetTopBar:     no
			isTesting:        no
			autoShow:         yes
		)

		alert('6')
	else
		alert('admob plugin not ready')

initApp = ->
	alert('3')
	initAd()
	window.plugins.AdMob.createBannerView()

onDocLoad = ->
	if /(ipad|iphone|ipod|android)/i.test(navigator.userAgent)
		alert('1')
		document.addEventListener('deviceready', initApp, no)
	else
		alert('2')
		initApp()

window.onload = ->
	onDocLoad()
 */
var AdMob, ad_units, admobid, initAd, initApp, onLoad;

alert('-1');

AdMob = window.plugins.AdMob;

onLoad = function() {
  alert('0');
  if (/(ipad|iphone|ipod|android)/i.test(navigator.userAgent)) {
    alert('1');
    return document.addEventListener('deviceready', initApp, false);
  } else {
    return initApp();
  }
};

ad_units = {
  ios: {
    banner: 'ca-app-pub-8910256399447461/6325603433',
    interstitial: 'ca-app-pub-8910256399447461/6325603433'
  },
  android: {
    banner: 'ca-app-pub-8910256399447461/6325603433',
    interstitial: 'ca-app-pub-8910256399447461/6325603433'
  }
};

admobid = /(android)/i.test(navigator.userAgent) ? ad_units.android : ad_units.ios;

initApp = function() {
  alert('2');
  if (!AdMob) {
    alert('admob plugin not ready');
    return;
  }
  initAd();
  return AdMob.createBanner(admobid.banner);
};

initAd = function() {
  var defaultOptions;
  alert('3');
  defaultOptions = {
    publisherId: admobid.banner,
    interstitialAdId: admobid.interstitial,
    adSize: 'SMART_BANNER',
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    isTesting: true,
    autoShow: true
  };
  return AdMob.setOptions(defaultOptions);
};
