// Generated by CoffeeScript 1.7.1
var confirm_reset, game_reset;

game_reset = document.getElementById('game-reset');

confirm_reset = document.getElementById('game-reset-confirm');

confirm_reset.style.display = 'none';

new Finger().add_event('tap', function(e) {
  switch (e.target.id) {
    case 'game-reset':
      return confirm_reset.style.display = confirm_reset.style.display === 'block' ? 'none' : 'block';
    case 'game-reset-confirm':
      localStorage.setItem('cur_level', 0);
      localStorage.setItem('go_level', 0);
      localStorage.setItem('medals', JSON.stringify({}));
      confirm_reset.style.display = 'none';
      game_reset.innerHTML = 'Remise &agrave; z&eacute;ro effectu&eacute;e';
      return game_reset.className = 'confirmed';
  }
});
