// Generated by CoffeeScript 1.7.1
new Finger().add_event('tap', function(e) {
  var target, _results;
  target = e.target;
  _results = [];
  while (target) {
    if (target.hasAttribute && target.hasAttribute('data-href')) {
      location.href = target.getAttribute('data-href');
      break;
    }
    _results.push(target = target.parentNode);
  }
  return _results;
});
